### ISSUE TITLE
Incessantly displays dialogs about binary files when used in windows

### ISSUE THREAD

**Issue by AlexanderGalen** [idleberg/sublime-applescript#4]
After adding the functionality to decode binary files on Mac, the plugin displays a dialog saying that you can only view binary files on mac every time you open a file, regardless of the file type.

For example, I was opening a php file and it kept bugging me. I had to disable the plugin to get it to stop.

**Comment by idleberg** [comment]
Thanks for reporting the issue. Quick fix in the new release, longterm fix when I get near a *real* computer 😉
