### ISSUE TITLE
edited files not "dirty"

### ISSUE THREAD

**Issue by trebitzki** [idleberg/sublime-applescript#5]
When I edit a .scpt file there is no indication that the file contains unsaved changes. The file tab has the x glyph, not the filled o circle. This is only with scpt files; no issue with others. I'm using ST3 on OS X 10.11.6.

**Comment by idleberg** [comment]
Thanks again, will have to investigate on that one

**Comment by trebitzki** [comment]
This also doesn't happen with .applescript files. The whole slew of issues came about because I was using binary .scpt files.
Closing this one!
