### ISSUE TITLE
applescript build changes file to binary

### ISSUE THREAD

**Issue by trebitzki** [idleberg/sublime-applescript#6]
When I build a script the file view changes to binary. I don't see a way of getting back the source code short of closing and reopening the file. ST3 on OS X 10.11.6.

**Comment by idleberg** [comment]
I think I tried every possible combination, but I cannot reproduce this one. You build a plain-text AppleScript file and on completion the scope changes to *AppleScript (Binary)*? Does the view change as well (e.g. to hex?)

**Comment by trebitzki** [comment]
Well it's a .scpt file I've been working with in Script Editor, compiling and running. I load it in ST3, edit and then build or run it. The scope is AppleScript (Binary) before and after building. When I load it I see the source code, after build it changes to hex.

**Comment by idleberg** [comment]
Ok, now I get it. You can just save the file and it will be compiled automatically, no need to build it. I'll have to check whether I can prevent building to avoid the issue you mentioned.

**Comment by trebitzki** [comment]
I think the issue is just with .scpt files, which are binary (although they show the source when first opened). When I create a file.applescript and add the same code I can build and run it fine and it stays plain-text. I've been working with the Script Editor before, that's why I thought .scpt files where the standard. Maybe you should mention in the ReadMe info that the plugin works best with the Applescript scope.

I can work with the editor fine now. Thanks for a great plugin!

**Comment by trebitzki** [comment]
All issues resolved!

**Comment by idleberg** [comment]
Just for the record: the Sublime Text API does not offer an `on_build` event, so I can't prevent binary files from being build a second time (which messes up the file). However, this can be undone running the *“AppleScript: Toggle Binary”* command.

**Comment by idleberg** [comment]
There is now a separate `.sublime-build` file for binary AppleScript. Using it, you can still run or build as App/Script Bundle.
