### ISSUE TITLE
'Building...' message in status bar

### ISSUE THREAD

**Issue by trebitzki** [idleberg/sublime-applescript#7]
As soon as I open a .scpt file the status bar message changes to "Saving as Binary Property List". No saving is going on and the message doesn't go away. ST3 on OS X 10.11.6.

Sorry for bombarding you with these issues. Having them separate makes it easier, I think.

**Comment by idleberg** [comment]
Thanks, that's a left-over from the BinaryPlist package (which served largely as the blueprint for this)

> Sorry for bombarding you with these issues. Having them separate makes it easier, I think.

No worries, that's the way to do it properly 😃

**Comment by trebitzki** [comment]
The message doesn't come up with .applescript files, so I'll close this one.
